Update methods to get rid of deprecation warning
Issafalcon/neotest-dotnet pull request #56
Opened 2023-04-17 09:26 UTC by JesperLundberg

Each time vim is started and tests are fun for the first time there is a warning about methods being deprecated in 0.10.

This is just a quick update which gets rid of them by using the new and recommended methods instead.

2023-04-17 10:43 UTC, Issafalcon requested changes
Thanks for the PR! These changes break older version of neovim, so just a couple of suggestions to modify the code.

Something like this is needed to make this backward compatible (the and .. or syntax is the lua equivalent of ternary operators).

2023-04-17 10:43 UTC, Issafalcon commented on lua/neotest-dotnet/frameworks/test-framework-utils.lua
> +  local parsed_query = vim.treesitter.query.parse("c_sharp", framework_query)
```suggestion
  local parsed_query = vim.fn.has("nvim-0.9.0") == 1 and vim.treesitter.query.parse("c_sharp", framework_query) or vim.treesitter.parse_query("c_sharp", framework_query)
```

2023-04-17 10:43 UTC, Issafalcon commented on lua/neotest-dotnet/frameworks/test-framework-utils.lua
> +    local test_attribute = vim.treesitter.get_node_text(captures[1], source)
```suggestion
    local test_attribute = vim.fn.has("nvim-0.9.0") == 1 and vim.treesitter.get_node_text(captures[1], source) or vim.treesitter.query.get_node_text(captures[1], source)
```

2023-04-17 18:48 UTC, JesperLundberg commented
Of course. That makes sense.

I come from the web development community where there are no versions. The current one is superceeded by the next one. No need to keep old versions active.

Thanks for the improvment. :)

2023-04-18 12:07 UTC, JesLun commented on lua/neotest-dotnet/frameworks/test-framework-utils.lua
> +  local parsed_query = vim.fn.has("nvim-0.9.0") == 1 and vim.treesitter.query.parse("c_sharp", framework_query) or vim.treesitter.parse_query("c_sharp", framework_query)
```suggestion
local parsed_query = vim.fn.has("nvim-0.9.0") == 1
    and vim.treesitter.query.parse("c_sharp", framework_query)
  or vim.treesitter.parse_query("c_sharp", framework_query)
```

2023-04-18 12:08 UTC, JesLun commented on lua/neotest-dotnet/frameworks/test-framework-utils.lua
> +    local test_attribute = vim.fn.has("nvim-0.9.0") == 1 and vim.treesitter.get_node_text(captures[1], source) or vim.treesitter.query.get_node_text(captures[1], source)
```suggestion
local test_attribute = vim.fn.has("nvim-0.9.0") == 1
    and vim.treesitter.get_node_text(captures[1], source)
  or vim.treesitter.query.get_node_text(captures[1], source)
```

2023-04-18 12:14 UTC, JesperLundberg commented
Ok, now all issues seem resolved.

(and yes, both these accounts are mine. One if my job one that I always forget to log out of for stuff like this)

2023-04-18 16:46 UTC, Issafalcon commented
> Of course. That makes sense.
> 
> I come from the web development community where there are no versions. The current one is superceeded by the next one. No need to keep old versions active.
> 
> Thanks for the improvment. :)

No worries. I'm also a web dev, so the backwards compatibility thing is something I'm getting used to!

2023-04-18 16:47 UTC, Issafalcon approved these changes

2023-04-18 16:47 UTC, merged